name: "Python Tox Test"
description: "Runs Tox environments using a specified Python version and environment"
inputs:
  python-version:
    description: "Python version to use for tox"
    required: false
    default: "3.12"
  tox-env:
    description: "Tox environment to run"
    required: false
    default: "docs"
  verbose:
    description: "Verbosity level (-v, -vv)"
    required: false
    default: "-vv"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install tox
      run: pip install tox
      shell: bash

    - name: Run tox
      run: tox -e ${{ inputs.tox-env }} ${{ inputs.verbose }}
      shell: bash
