---
name: run-github-merge
description: 'Automatically merges a pull request into a protected branch'
author: OpenTelekomCloud Ecosystem squad
inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  base_branch:
    description: 'The branch to merge into'
    required: true
  pr_number:
    description: 'The pull request number to merge'
    required: true
runs:
  using: docker
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.base_branch }}
    - ${{ inputs.pr_number }}
