---
name: python-lint

on:
  pull_request:
    types:
      - opened
      - closed
      - edited
      - reopened
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.11]
    steps:
      - uses: advanced-security/python-lint-code-scanning-action@v1
        with:
          linter: flake8
          python-version: ${{ matrix.python-version }}
